apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-blue-config
  namespace: registration-app
data:
  PORT: "3100"
  BACKEND_URL: "http://backend:5000"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-green-config
  namespace: registration-app
data:
  PORT: "3200"
  BACKEND_URL: "http://backend:5000"
